## c3
## Copyright 2022 Thomas de Grivel <thoxdg@gmail.com>

all: c3c

CLEANFILES = c3c .libs *.lo *.la

DISTCLEANFILES = ${CLEANFILES} config.mk

clean:
	rm -rf ${CLEANFILES}

distclean:
	rm -rf ${DISTCLEANFILES}

.PHONY: all clean distclean

include config.mk
